name: test

on:
  push:
  pull_request:
    branches:
      - main
  schedule:
    # At 06:00am every Saturday (for new versions of rustc)
    - cron:  '0 6 * * 6'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Check code format
        run: cargo fmt -- --check

      - name: Run all tests
        run: cargo test --all-features